# Generated by Django 5.0.6 on 2024-10-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='mobile_number',
        ),
    ]
